Traceback (most recent call last):
  File "/home/bitzer/SoftDev/Python/ScienceEnv/SE/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/bitzer/SoftDev/Python/ScienceEnv/SE/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/bitzer/SoftDev/Python/ScienceEnv/SE/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/bitzer/SoftDev/Python/ScienceEnv/SE/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/bitzer/SoftDev/Python/ScienceEnv/SE/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/home/bitzer/SoftDev/Python/ScienceEnv/SE/lib/python3.9/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/bitzer/SoftDev/Python/ScienceEnv/SE/lib/python3.9/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib
import numpy
from matplotlib import pyplot
from myst_nb import glue

matplotlib.style.use('sv.mplstyle')

index = [0, 1, 2, 3, 4, 5, 6]
input = [1, 0.5, 1]
x0 = [1, 0, 0]
x1 = [0, 0.5, 0]
x2 = [0, 0, 1]
system = [0.5, 0.75, 1]

fig, ((ax_input, ax_system),(ax_x0, ax_yx0),(ax_x1, ax_yx1),(ax_x2, ax_yx2),(ax_empty, ax_sum)) = pyplot.subplots(5, 2, sharex='all', sharey='all')

#fig1, ax_input = pyplot.subplots()
#fig2, ax_system = pyplot.subplots()
#fig3, ax_x0 = pyplot.subplots()
#fig4, ax_ax_yx0 = pyplot.subplots()
#fig5, ax_x1 = pyplot.subplots()
#fig6, ax_yx1 = pyplot.subplots()
#fig7, ax_x2 = pyplot.subplots()
#fig8, ax_yx2 = pyplot.subplots()
#fig10, ax_sum = pyplot.subplots()



ax_input.stem(input + [0, 0], use_line_collection=True)
ax_input.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', title='Inputsignal', xlim=[0, 6], ylim=[0, 2])

ax_system.stem(system + [0, 0], use_line_collection=True)
ax_system.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', title='System', xlim=[0, 6], ylim=[0, 2])

ax_x0.stem(x0, use_line_collection=True)
ax_x0.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', title='Input bei x[0]', xlim=[0, 6], ylim=[0, 2])

y_x_0 = numpy.convolve(x0, system)

ax_yx0.stem(y_x_0, use_line_collection=True)
ax_yx0.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', title='Systemantwort f√ºr x[0]', xlim=[0, 6], ylim=[0, 2])


ax_x1.stem(x1, use_line_collection=True)
ax_x1.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', title='Input bei x[1]', xlim=[0, 6], ylim=[0, 2])


y_x_1 = numpy.convolve(x1, system)
ax_yx1.stem(y_x_1, use_line_collection=True)
ax_yx1.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', title='Systemantwort f√ºr x[1]', xlim=[0, 6], ylim=[0, 2])


ax_x2.stem(x2, use_line_collection=True)
ax_x2.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', title='Input bei x[2]', xlim=[0, 6], ylim=[0, 2])

y_x_2 = numpy.convolve(x2, system)
ax_yx2.stem(y_x_2, use_line_collection=True)
ax_yx2.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', title='Systemantwort f√ºr x[2]', xlim=[0, 6], ylim=[0, 2])

conv_sum = numpy.convolve(input, system)
ax_sum.stem(conv_sum, use_line_collection=True)
ax_sum.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', title='Systemantwort f√ºr Inputsignal', xlim=[0, 6], ylim=[0, 2])

#pyplot.tight_layout()
#pyplot.show()
glue("FaltungErklaerung", fig, display=False)


#glue("FaltungErklaerung1", fig1, display=False)
#glue("FaltungErklaerung2", fig2, display=False)
#glue("FaltungErklaerung3", fig3, display=False)
#glue("FaltungErklaerung4", fig4, display=False)
#glue("FaltungErklaerung5", fig5, display=False)
#glue("FaltungErklaerung6", fig6, display=False)
#glue("FaltungErklaerung7", fig7, display=False)
#glue("FaltungErklaerung8", fig8, display=False)
#glue("FaltungErklaerung10", fig10, display=False)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/tmp/ipykernel_150808/1096807132.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mimport[0m [0mmatplotlib[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mimport[0m [0mnumpy[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;32mfrom[0m [0mmatplotlib[0m [0;32mimport[0m [0mpyplot[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;32mfrom[0m [0mmyst_nb[0m [0;32mimport[0m [0mglue[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'matplotlib'
ModuleNotFoundError: No module named 'matplotlib'

